// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmfJJgfacVAYNcihFPJIW1xR8eZMLhu1Y',
    appId: '1:328529430929:web:68590f00ee2a4a7fffb230',
    messagingSenderId: '328529430929',
    projectId: 'train-983ae',
    authDomain: 'train-983ae.firebaseapp.com',
    databaseURL: 'https://train-983ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-983ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FyaqYfaUu2HN-xGevUdqYHXwSD7iO2w',
    appId: '1:328529430929:android:1d578bbf588c9169ffb230',
    messagingSenderId: '328529430929',
    projectId: 'train-983ae',
    databaseURL: 'https://train-983ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-983ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO64XL5uAAjSqMlryAllWQ3smFQctKkKk',
    appId: '1:328529430929:ios:5b614f3f4306a8f1ffb230',
    messagingSenderId: '328529430929',
    projectId: 'train-983ae',
    databaseURL: 'https://train-983ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-983ae.appspot.com',
    iosClientId: '328529430929-k6o6lfqdneck38ag7u1t2o0vk0rrg3qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO64XL5uAAjSqMlryAllWQ3smFQctKkKk',
    appId: '1:328529430929:ios:5b614f3f4306a8f1ffb230',
    messagingSenderId: '328529430929',
    projectId: 'train-983ae',
    databaseURL: 'https://train-983ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'train-983ae.appspot.com',
    iosClientId: '328529430929-k6o6lfqdneck38ag7u1t2o0vk0rrg3qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrition',
  );
}
